# Main config for @project.name@ @project.version@
enabled: true

# Plugin locale
# Currently included: en_US, ru_RU
language: 'en_US'

# Geological radius of picks
woodenPickaxeRadius: 0
stonePickaxeRadius: 3
ironPickaxeRadius: 4
goldenPickaxeRadius: 4
diamondPickaxeRadius: 5
netheritePickaxeRadius: 5

# Deal damage to the pickaxe when using
damagePickaxe: true

# Find chance
oreChances:
  COAL_ORE: 1.0
  COPPER_ORE: 1.0
  IRON_ORE: 1.0
  LAPIS_ORE: 0.75
  GOLD_ORE: 0.75
  REDSTONE_ORE: 0.75
  DIAMOND_ORE: 0.50
  EMERALD_ORE: 0.50
  DEEPSLATE_COAL_ORE: 0.75
  DEEPSLATE_COPPER_ORE: 0.75
  DEEPSLATE_IRON_ORE: 0.75
  DEEPSLATE_LAPIS_ORE: 0.50
  DEEPSLATE_GOLD_ORE: 0.50
  DEEPSLATE_REDSTONE_ORE: 0.50
  DEEPSLATE_DIAMOND_ORE: 0.25
  DEEPSLATE_EMERALD_ORE: 0.25
  NETHER_GOLD_ORE: 1.0
  NETHER_QUARTZ_ORE: 1.0