package ru.izerus.sibgeology.config;

public enum Lang {

	RELOADED, ORE_NOT_FOUND, WEAK_PICKAXE, COAL_ORE, COPPER_ORE, DIAMOND_ORE, EMERALD_ORE, GOLD_ORE, IRON_ORE,
	LAPIS_ORE, REDSTONE_ORE, DEEPSLATE_COAL_ORE, DEEPSLATE_COPPER_ORE, DEEPSLATE_DIAMOND_ORE, DEEPSLATE_EMERALD_ORE,
	DEEPSLATE_GOLD_ORE, DEEPSLATE_IRON_ORE, DEEPSLATE_LAPIS_ORE, DEEPSLATE_REDSTONE_ORE, NETHER_GOLD_ORE,
	NETHER_QUARTZ_ORE,

}
